# Image de base
FROM python:3.9

# Définition des variables d'environnement pour Python unbuffered
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Création d'un répertoire pour contenir l'application
WORKDIR /app

# Installation des dépendances
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copie du reste du code de l'application
COPY . /app/

# Exposition du port
EXPOSE 8000

# Commande pour démarrer l'application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
