name: Django CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./end_project
    - name: Run tests with coverage
      run: |
        pytest --cov=./ --cov-report=term --cov-fail-under=80
      working-directory: ./end_project
